export const INTIM_2026_EVENT = {
  slug: "probuild-intim-2026",
  name: "ProBuild INTIM 2026",
  description: "Pendaftaran visitor ProBuild INTIM 2026",
  registrationPrefix: "RSVP-2026",
  isActive: true,
} as const;

export const INTIM_2026_FIELDS = [
  {
    key: "email",
    labelId: "Email",
    labelEn: "Email",
    type: "email",
    required: true,
    sortOrder: 1,
    showInTable: true,
    indexAs: "email",
    uniquePerEvent: true,
    validation: {},
  },
  {
    key: "fullName",
    labelId: "Nama lengkap",
    labelEn: "Full name",
    type: "text",
    required: true,
    sortOrder: 2,
    showInTable: true,
    indexAs: "fullName",
    uniquePerEvent: false,
    validation: { minLength: 3, maxLength: 255 },
  },
  {
    key: "whatsapp",
    labelId: "Nomor WhatsApp",
    labelEn: "WhatsApp number",
    type: "tel",
    required: true,
    sortOrder: 3,
    showInTable: true,
    indexAs: "phone",
    uniquePerEvent: true,
    validation: { pattern: "^\\d{8,16}$" },
  },
  {
    key: "institution",
    labelId: "Nama perusahaan / instansi",
    labelEn: "Company / institution",
    type: "text",
    required: true,
    sortOrder: 4,
    showInTable: true,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
  },
  {
    key: "position",
    labelId: "Jabatan",
    labelEn: "Position",
    type: "text",
    required: false,
    sortOrder: 5,
    showInTable: true,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
  },
] as const;
