export const INTIM_2026_EVENT = {
  slug: "probuild-intim-2026",
  name: "ProBuild INTIM 2026",
  description: "Pendaftaran visitor ProBuild INTIM 2026",
  registrationPrefix: "RSVP-2026",
  isActive: true,
} as const;

/**
 * Skema form visitor (kolom dashboard = showInTable).
 * Wajib hanya field yang dikirim form expo (/registrasi):
 * fullName, email, whatsapp, institution, termsAccepted, language.
 * Sisanya opsional agar payload singkat tidak bentrok validasi.
 */
export const INTIM_2026_FIELDS = [
  {
    key: "fullName",
    labelId: "Nama lengkap beserta gelar",
    labelEn: "Full name with title",
    type: "text",
    required: true,
    sortOrder: 1,
    showInTable: true,
    indexAs: "fullName",
    uniquePerEvent: false,
    validation: { minLength: 3, maxLength: 255 },
  },
  {
    key: "position",
    labelId: "Jabatan",
    labelEn: "Position",
    type: "text",
    required: false,
    sortOrder: 2,
    showInTable: true,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
  },
  {
    key: "institution",
    labelId: "Nama lembaga/perusahaan",
    labelEn: "Institution / company",
    type: "text",
    required: true,
    sortOrder: 3,
    showInTable: true,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
  },
  {
    key: "institutionAddress",
    labelId: "Alamat instansi (kota & provinsi)",
    labelEn: "Institution address (city & province)",
    type: "text",
    required: false,
    sortOrder: 4,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 5, maxLength: 500 },
  },
  {
    key: "identityNumber",
    labelId: "Nomor KTP",
    labelEn: "ID card number",
    type: "tel",
    required: false,
    sortOrder: 5,
    showInTable: false,
    indexAs: "identityNumber",
    uniquePerEvent: true,
    validation: { pattern: "^\\d{16}$", exactLength: 16 },
  },
  {
    key: "whatsapp",
    labelId: "Nomor WhatsApp",
    labelEn: "WhatsApp number",
    type: "tel",
    required: true,
    sortOrder: 6,
    showInTable: true,
    indexAs: "phone",
    uniquePerEvent: true,
    validation: { pattern: "^\\d{8,16}$" },
  },
  {
    key: "email",
    labelId: "Email",
    labelEn: "Email",
    type: "email",
    required: true,
    sortOrder: 7,
    showInTable: true,
    indexAs: "email",
    uniquePerEvent: true,
    validation: {},
  },
  {
    key: "partySize",
    labelId: "Jumlah rombongan (termasuk diri sendiri)",
    labelEn: "Party size (including yourself)",
    type: "number",
    required: false,
    sortOrder: 8,
    showInTable: true,
    indexAs: null,
    uniquePerEvent: false,
    validation: { min: 1, max: 10 },
  },
  {
    key: "groupMembers",
    labelId: "Anggota rombongan",
    labelEn: "Group members",
    type: "group",
    required: false,
    sortOrder: 9,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: {
      itemFields: [
        { key: "name", minLength: 2, required: true },
        { key: "position", minLength: 2, required: true },
      ],
      lengthEqualsField: "partySize",
      offset: -1,
    },
    conditions: {
      requiredIf: { field: "partySize", gt: 1 },
      showIf: { field: "partySize", gt: 1 },
    },
  },
  {
    key: "attendanceStatus",
    labelId: "Konfirmasi kehadiran",
    labelEn: "Attendance status",
    type: "select",
    required: false,
    sortOrder: 10,
    showInTable: true,
    indexAs: null,
    uniquePerEvent: false,
    options: [
      { value: "hadir", labelId: "Hadir", labelEn: "Attending" },
      { value: "diwakilkan", labelId: "Diwakilkan", labelEn: "Represented" },
      {
        value: "berhalangan",
        labelId: "Berhalangan hadir",
        labelEn: "Unable to attend",
      },
    ],
  },
  {
    key: "delegateName",
    labelId: "Nama perwakilan",
    labelEn: "Delegate name",
    type: "text",
    required: false,
    sortOrder: 11,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
    conditions: {
      requiredIf: { field: "attendanceStatus", eq: "diwakilkan" },
      showIf: { field: "attendanceStatus", eq: "diwakilkan" },
    },
  },
  {
    key: "delegatePosition",
    labelId: "Jabatan perwakilan",
    labelEn: "Delegate position",
    type: "text",
    required: false,
    sortOrder: 12,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
    conditions: {
      requiredIf: { field: "attendanceStatus", eq: "diwakilkan" },
      showIf: { field: "attendanceStatus", eq: "diwakilkan" },
    },
  },
  {
    key: "eventRoles",
    labelId: "Rencana peran dalam acara",
    labelEn: "Planned event roles",
    type: "multiselect",
    required: false,
    sortOrder: 13,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minItems: 1 },
    options: [
      {
        value: "pembuka_sambutan",
        labelId: "Pembuka Sambutan",
        labelEn: "Opening remarks",
      },
      { value: "narasumber", labelId: "Narasumber", labelEn: "Speaker" },
      {
        value: "peninjau_stand",
        labelId: "Peninjau Stand",
        labelEn: "Booth visitor",
      },
      {
        value: "tamu_undangan",
        labelId: "Tamu Undangan",
        labelEn: "Invited guest",
      },
      { value: "lainnya", labelId: "Lainnya", labelEn: "Other" },
    ],
  },
  {
    key: "eventRolesOther",
    labelId: "Keterangan peran lainnya",
    labelEn: "Other role description",
    type: "text",
    required: false,
    sortOrder: 14,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minLength: 2, maxLength: 255 },
    conditions: {
      requiredIf: { field: "eventRoles", contains: "lainnya" },
      showIf: { field: "eventRoles", contains: "lainnya" },
    },
  },
  {
    key: "specialNeeds",
    labelId: "Kebutuhan khusus",
    labelEn: "Special needs",
    type: "multiselect",
    required: false,
    sortOrder: 15,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { minItems: 1 },
    options: [
      { value: "kursi_roda", labelId: "Kursi roda", labelEn: "Wheelchair" },
      {
        value: "akses_prioritas",
        labelId: "Akses prioritas",
        labelEn: "Priority access",
      },
      { value: "meja_khusus", labelId: "Meja khusus", labelEn: "Special table" },
      { value: "penerjemah", labelId: "Penerjemah", labelEn: "Interpreter" },
      { value: "tidak_ada", labelId: "Tidak ada", labelEn: "None" },
    ],
  },
  {
    key: "notes",
    labelId: "Catatan untuk panitia",
    labelEn: "Notes for the committee",
    type: "textarea",
    required: false,
    sortOrder: 16,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { maxLength: 2000 },
  },
  {
    key: "termsAccepted",
    labelId: "Persetujuan ketentuan acara",
    labelEn: "Accept event terms",
    type: "boolean",
    required: true,
    sortOrder: 17,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    validation: { mustBe: true },
  },
  {
    key: "language",
    labelId: "Bahasa form",
    labelEn: "Form language",
    type: "select",
    required: true,
    sortOrder: 18,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
    options: [
      { value: "id", labelId: "Indonesia", labelEn: "Indonesian" },
      { value: "en", labelId: "English", labelEn: "English" },
    ],
  },
  {
    key: "submittedAt",
    labelId: "Waktu submit (klien)",
    labelEn: "Client submitted at",
    type: "text",
    required: false,
    sortOrder: 19,
    showInTable: false,
    indexAs: null,
    uniquePerEvent: false,
  },
] as const;
